# .buildkite/pipeline.yml

steps:

  
  - label: ":lock: Snyk Scan Locally"
    command: "snyk test --severity-threshold=high"
    agents:
      queue: "default"
    plugins:
      - docker#v3.7.0:
          image: "snyk/snyk:node"
          always-pull: true

  - wait
  - label: ":lock: Snyk Test in Build"
    command: "snyk test --severity-threshold=high --fail-on=all"
    agents:
      queue: "default"
    plugins:
      - docker#v3.7.0:
          image: "snyk/snyk:node"
          always-pull: true
    env:
      - SNYK_TOKEN= ae4e4eed-8f40-4707-bcec-828661fdf31f  

steps:
  - name: "Snyk testing"
    plugins:
      - seek-oss/aws-sm#v0.0.5:
          env:
            SNYK_TOKEN: ae4e4eed-8f40-4707-bcec-828661fdf31f  
      - seek-oss/snyk#v1.0.0:
          block: true
          language: node
          path: package.json
          severity: low
          npmToken: NPM_TOKEN
          org: test-team
    agents: 
      queue: "default"
      
  - label: ":hammer: Build and Secrets Plugin"
    command: "npm install && npm test"  
    agents:
      queue: "default"
    plugins:
      - aws-ssm#v1.0.0:
          parameters:
            PARAMETER_ONE: "/test-param"
            PARAMETER_TWO: "/test-parameter"
          ssh: true
          
      - docker#v3.7.0:
          image: "node:20-alpine"
          always-pull: true
    env:
      - SNYK_TOKEN=ae4e4eed-8f40-4707-bcec-828661fdf31f   
      # - ANOTHER_SECRET=${SECRETS_TEST_PARAMETER}  


      
