# .buildkite/pipeline.yml

steps:
  - label: ":lock: Snyk Test in Build"
    command: "snyk test --severity-threshold=high --fail-on=all"
    agents:
      queue: "default"
    plugins:
      - docker#v3.7.0:
          image: "snyk/snyk:node"
          always-pull: true
    env:
      - SNYK_TOKEN=ae4e4eed-8f40-4707-bcec-828661fdf31f  
  
  # - label: ":lock: Snyk Scan Locally"
  #   command: "snyk test --severity-threshold=high"
  #   agents:
  #     queue: "default"
  #   plugins:
  #     - docker#v3.7.0:
  #         image: "snyk/snyk:node"
  #         always-pull: true

  - wait

  - label: ":hammer: Build and Secrets Plugin"
    command: "npm install && npm test"  
    agents:
      queue: "default"
    plugins:
      - aws-ssm#v1.0.0:
          parameters:
            PARAMETER_ONE: "/test-param"
            PARAMETER_TWO: "/test-parameter"
          ssh: true
          
      - docker#v3.7.0:
          image: "snyk/snyk:node"
          always-pull: true
    env:
      - SNYK_TOKEN=ae4e4eed-8f40-4707-bcec-828661fdf31f   
      # - ANOTHER_SECRET=${SECRETS_TEST_PARAMETER}  


      
